export enum RabbitMQ {
  VeterinarioQueue = 'veterinario',
}

export enum VeterinarioMsg {
  CREATE = 'CREATE_VETERINARIO',
  FIND_ALL = 'FIND_VETERINARIOS',
  FIND_ONE = 'FIND_VETERINARIO',
  UPDATE = 'UPDATE_VETERINARIO',
  DELETE = 'DELETE_VETERINARIO',
  ADD_VETERINARIO = 'ADD_VETERINARIO',
}